module: envs
name: AntPinpad-v0
seed: 0
steps: 1
num_env: 1
vecnormalize: true
config:
  intrinsic_scale: 12.0
  subgoal_reward: 2.0
  survival_reward: 0.1
  posture_penalty_coef: 10.0
  posture_penalty_threshold: 0.7
  fall_penalty: 10.0